---
# service_to_save_list_of_installed_rpms/tasks/main.yml

- name: "Create directory {{ rpm_backup_directory }}"
  ansible.builtin.file:
    path: "{{ rpm_backup_directory }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Create shell script'
  ansible.builtin.template:
    src: 'save_list_of_installed_rpms.sh.j2'
    dest: '/usr/local/bin/save_list_of_installed_rpms.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Create systemd services'
  ansible.builtin.template:
    src: 'save_list_of_installed_rpms.service.j2'
    dest: '/etc/systemd/system/save_list_of_installed_rpms.service'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Start the systemd services'
  ansible.builtin.systemd:
    name: 'save_list_of_installed_rpms.service'
    state: 'started'
    enabled: true
    daemon_reload: true
